### ISSUE TITLE
最终一致性是否能保证一致性?

### ISSUE THREAD

**Issue by tzm1119** [RayTale/Vertex#120]
最终一致性模型，能保证数据一致性问题吗？比如在RaiseEvent方法中，保存事件到EventStorage成功了，但是在EventStream.Next的过程中，出现了异常，比如一个VertexAcotr有3个FlowActor，在VertexAcotr触发事件的过程，前两个FlowActor的事件处理都成功了，但是最后一个FlowActor的处理失败了，这是仅回退VertexAcotr的快照是不是 不行啊

**Comment by u-less** [comment]
这个需要自己控制是要回退还是如何处理，框架会保证消息一定会被正常消费一次，如果出现异常会重复送达
